import type { DialoguePhrase } from './types.ts';

const SHARED_HOME_PHRASES = [
  { id: 'home-welcome-01', context: 'home', text: 'Ready when you are.' },
  {
    id: 'home-welcome-02',
    context: 'home',
    text: 'A little practice can make a big difference.',
  },
  {
    id: 'home-welcome-03',
    context: 'home',
    text: '{companion} saved you a cozy spot.',
  },
  {
    id: 'home-welcome-04',
    context: 'home',
    text: 'What kind of challenge sounds fun today?',
  },
  {
    id: 'home-welcome-05',
    context: 'home',
    text: 'Your Number Nook is ready for another visit.',
  },
  {
    id: 'home-welcome-06',
    context: 'home',
    text: 'Small steps still move your skills forward.',
  },
  {
    id: 'home-warm-01',
    context: 'home',
    text: 'It is always good to see you back in the Nook.',
    voices: ['warm'],
  },
  {
    id: 'home-playful-01',
    context: 'home',
    text: 'There are fresh questions waiting to be discovered.',
    voices: ['playful'],
  },
  {
    id: 'home-dreamy-01',
    context: 'home',
    text: 'A quiet little challenge is waiting for you.',
    voices: ['dreamy'],
  },
  {
    id: 'home-thoughtful-01',
    context: 'home',
    text: 'Take your time and notice what feels easier today.',
    voices: ['thoughtful'],
  },
  {
    id: 'home-adventurous-01',
    context: 'home',
    text: 'Another trail of number puzzles is ready!',
    voices: ['adventurous'],
  },
  {
    id: 'home-inventive-01',
    context: 'home',
    text: 'Let us see which number patterns click today.',
    voices: ['inventive'],
  },
  {
    id: 'home-plush-01',
    context: 'home',
    text: 'Everything is tucked in and ready for practice.',
    voices: ['plush'],
  },
  {
    id: 'home-welcome-07',
    context: 'home',
    text: 'You choose the challenge, and {companion} will come along.',
  },
  {
    id: 'home-welcome-08',
    context: 'home',
    text: 'A quick round is a great way to keep growing.',
  },
] as const satisfies readonly DialoguePhrase[];

const SHARED_SETUP_PHRASES = [
  { id: 'setup-ready-01', context: 'setup', text: 'Pick a challenge that feels right today.' },
  { id: 'setup-ready-02', context: 'setup', text: 'You can practice one skill or mix things up.' },
  { id: 'setup-ready-03', context: 'setup', text: 'A careful round starts with a good plan.' },
  { id: 'setup-ready-04', context: 'setup', text: '{companion} is ready for your next round.' },
  {
    id: 'setup-ready-05',
    context: 'setup',
    text: 'Choose your challenge, then take it one question at a time.',
  },
  {
    id: 'setup-warm-01',
    context: 'setup',
    text: 'There is no rush. Choose what you would like to practice.',
    voices: ['warm'],
  },
  {
    id: 'setup-playful-01',
    context: 'setup',
    text: 'Which set of questions should we open first?',
    voices: ['playful'],
  },
  {
    id: 'setup-dreamy-01',
    context: 'setup',
    text: 'Settle in and choose a number path to follow.',
    voices: ['dreamy'],
  },
  {
    id: 'setup-thoughtful-01',
    context: 'setup',
    text: '{operation} practice sounds like a thoughtful choice.',
    voices: ['thoughtful'],
  },
  {
    id: 'setup-adventurous-01',
    context: 'setup',
    text: 'Choose the trail. {companion} is ready to explore it.',
    voices: ['adventurous'],
  },
  {
    id: 'setup-inventive-01',
    context: 'setup',
    text: 'Tune the settings until this round fits just right.',
    voices: ['inventive'],
  },
  {
    id: 'setup-plush-01',
    context: 'setup',
    text: 'Everything is buttoned up whenever you are ready.',
    voices: ['plush'],
  },
] as const satisfies readonly DialoguePhrase[];

const SHARED_RESULT_PHRASES = [
  {
    id: 'results-practice-01',
    context: 'results',
    text: 'Every question you tried strengthened your skills.',
  },
  { id: 'results-practice-02', context: 'results', text: 'That practice belongs to you now.' },
  {
    id: 'results-practice-03',
    context: 'results',
    text: 'You gave your number skills a useful workout.',
  },
  {
    id: 'results-practice-04',
    context: 'results',
    text: '{companion} is cheering for the practice you put in.',
  },
  {
    id: 'results-practice-05',
    context: 'results',
    text: 'Another round complete and another step forward.',
  },
  {
    id: 'results-practice-06',
    context: 'results',
    text: 'You stayed with the challenge all the way through.',
  },
  {
    id: 'results-practice-07',
    context: 'results',
    text: 'Practice adds up, one thoughtful answer at a time.',
  },
  {
    id: 'results-practice-08',
    context: 'results',
    text: 'You completed the round with {accuracy} accuracy.',
  },
  {
    id: 'results-warm-01',
    context: 'results',
    text: 'That was time well spent practicing.',
    voices: ['warm'],
  },
  {
    id: 'results-playful-01',
    context: 'results',
    text: 'Those questions kept things interesting!',
    voices: ['playful'],
  },
  {
    id: 'results-thoughtful-01',
    context: 'results',
    text: 'Notice what felt easier by the end of the round.',
    voices: ['thoughtful'],
  },
  {
    id: 'results-strong-accuracy-01',
    context: 'results',
    text: 'Careful work made this a very accurate round.',
  },
  {
    id: 'results-first-round-01',
    context: 'results',
    text: 'Your first round is complete. That is a wonderful place to begin.',
    condition: { firstRound: true },
  },
  {
    id: 'results-first-round-02',
    context: 'results',
    text: '{companion} loved joining you for your first round.',
    condition: { firstRound: true },
  },
  {
    id: 'results-first-round-03',
    context: 'results',
    text: 'You just made your first Number Nook score!',
    condition: { firstRound: true },
  },
  {
    id: 'results-first-round-04',
    context: 'results',
    text: 'One round down, with plenty of room for new discoveries.',
    condition: { firstRound: true },
  },
  {
    id: 'results-perfect-01',
    context: 'results',
    text: 'A clean sweep! Every answer landed.',
    condition: { perfect: true },
  },
  {
    id: 'results-perfect-02',
    context: 'results',
    text: '{companion} counted every answer, and every one was right!',
    condition: { perfect: true },
  },
  {
    id: 'results-perfect-03',
    context: 'results',
    text: 'Perfect accuracy made that round sparkle.',
    condition: { perfect: true },
  },
  {
    id: 'results-perfect-04',
    context: 'results',
    text: 'You solved the whole set without missing one.',
    condition: { perfect: true },
  },
  {
    id: 'results-perfect-05',
    context: 'results',
    text: 'Every question found its answer. Nicely done!',
    condition: { perfect: true },
  },
  {
    id: 'results-perfect-06',
    context: 'results',
    text: 'That was {accuracy} accuracy from start to finish.',
    condition: { perfect: true },
  },
  {
    id: 'results-personal-best-01',
    context: 'results',
    text: 'That is your new personal best!',
    condition: { personalBest: true },
  },
  {
    id: 'results-personal-best-02',
    context: 'results',
    text: '{companion} just watched you set a brand-new best score.',
    condition: { personalBest: true },
  },
  {
    id: 'results-personal-best-03',
    context: 'results',
    text: 'Your practice just raised the bar.',
    condition: { personalBest: true },
  },
  {
    id: 'results-personal-best-04',
    context: 'results',
    text: 'A new best is a fine reason to celebrate.',
    condition: { personalBest: true },
  },
  {
    id: 'results-personal-best-05',
    context: 'results',
    text: 'That round became the score to beat next time.',
    condition: { personalBest: true },
  },
  {
    id: 'results-personal-best-06',
    context: 'results',
    text: 'You found a new level of your own.',
    condition: { personalBest: true },
  },
  {
    id: 'results-accuracy-improved-01',
    context: 'results',
    text: 'Your careful work made this round more accurate.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-accuracy-improved-02',
    context: 'results',
    text: '{companion} noticed that more answers clicked this time.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-accuracy-improved-03',
    context: 'results',
    text: 'That improvement came from the work you put in.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-accuracy-improved-04',
    context: 'results',
    text: 'You turned practice into greater accuracy.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-accuracy-improved-05',
    context: 'results',
    text: 'This round was steadier than the last one.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-accuracy-improved-06',
    context: 'results',
    text: 'More of those number patterns are settling into place.',
    condition: { accuracyImproved: true },
  },
  {
    id: 'results-pace-improved-01',
    context: 'results',
    text: 'That round moved more smoothly than before.',
    condition: { paceImproved: true },
  },
  {
    id: 'results-pace-improved-02',
    context: 'results',
    text: '{companion} noticed your answers finding their rhythm.',
    condition: { paceImproved: true },
  },
  {
    id: 'results-pace-improved-03',
    context: 'results',
    text: 'You kept your careful work and found a quicker pace.',
    condition: { paceImproved: true },
  },
  {
    id: 'results-pace-improved-04',
    context: 'results',
    text: 'Those answers arrived with a little more ease.',
    condition: { paceImproved: true },
  },
  {
    id: 'results-pace-improved-05',
    context: 'results',
    text: 'Your number sense is finding a comfortable rhythm.',
    condition: { paceImproved: true },
  },
  {
    id: 'results-pace-improved-06',
    context: 'results',
    text: 'Smooth and steady—that practice is showing.',
    condition: { paceImproved: true },
  },
] as const satisfies readonly DialoguePhrase[];

const SHARED_CAPSULE_PHRASES = [
  { id: 'capsule-curious-01', context: 'capsule', text: 'Who do you think is waiting inside?' },
  {
    id: 'capsule-curious-02',
    context: 'capsule',
    text: '{companion} is curious to meet someone new.',
  },
  {
    id: 'capsule-curious-03',
    context: 'capsule',
    text: 'Every unopened capsule holds a new possibility.',
  },
  {
    id: 'capsule-curious-04',
    context: 'capsule',
    text: 'The Nook always has room for one more friend.',
  },
  {
    id: 'capsule-curious-05',
    context: 'capsule',
    text: 'A mystery companion may be just one opening away.',
  },
  {
    id: 'capsule-playful-01',
    context: 'capsule',
    text: 'That capsule looks ready to pop!',
    voices: ['playful'],
  },
  {
    id: 'capsule-dreamy-01',
    context: 'capsule',
    text: 'There is a little mystery glowing in there.',
    voices: ['dreamy'],
  },
  {
    id: 'capsule-adventurous-01',
    context: 'capsule',
    text: 'A new friend could be the start of a new adventure.',
    voices: ['adventurous'],
  },
  {
    id: 'capsule-inventive-01',
    context: 'capsule',
    text: 'The capsule gears are ready whenever you are.',
    voices: ['inventive'],
  },
  {
    id: 'capsule-plush-01',
    context: 'capsule',
    text: 'Someone cozy might be tucked inside.',
    voices: ['plush'],
  },
] as const satisfies readonly DialoguePhrase[];

const SHARED_EQUIP_PHRASES = [
  { id: 'equip-ready-01', context: 'equip', text: '{companion} is ready to join you.' },
  { id: 'equip-ready-02', context: 'equip', text: 'Your new companion is by your side.' },
  { id: 'equip-ready-03', context: 'equip', text: 'The Nook has a fresh new feeling.' },
  {
    id: 'equip-ready-04',
    context: 'equip',
    text: '{companion} brought a favorite color palette along.',
  },
  {
    id: 'equip-warm-01',
    context: 'equip',
    text: 'This looks like the beginning of a good practice team.',
    voices: ['warm'],
  },
  {
    id: 'equip-playful-01',
    context: 'equip',
    text: 'New companion, new look, same Number Nook!',
    voices: ['playful'],
  },
  {
    id: 'equip-adventurous-01',
    context: 'equip',
    text: '{companion} is packed and ready for the next challenge.',
    voices: ['adventurous'],
  },
  {
    id: 'equip-plush-01',
    context: 'equip',
    text: '{companion} fits right into the coziest corner.',
    voices: ['plush'],
  },
] as const satisfies readonly DialoguePhrase[];

const SHARED_PROGRESS_PHRASES = [
  {
    id: 'progress-reflect-01',
    context: 'progress',
    text: 'Every finished round is part of your progress.',
  },
  {
    id: 'progress-reflect-02',
    context: 'progress',
    text: 'Look how much practice you have collected.',
  },
  {
    id: 'progress-reflect-03',
    context: 'progress',
    text: '{companion} likes seeing all those rounds add up.',
  },
  {
    id: 'progress-reflect-04',
    context: 'progress',
    text: 'Your history shows the work behind your skills.',
  },
  {
    id: 'progress-reflect-05',
    context: 'progress',
    text: 'Progress can be quick, quiet, or one question at a time.',
  },
  {
    id: 'progress-warm-01',
    context: 'progress',
    text: 'There is plenty here to feel good about.',
    voices: ['warm'],
  },
  {
    id: 'progress-dreamy-01',
    context: 'progress',
    text: 'Each round is another bright point in the picture.',
    voices: ['dreamy'],
  },
  {
    id: 'progress-thoughtful-01',
    context: 'progress',
    text: 'Your results can help you choose what to practice next.',
    voices: ['thoughtful'],
  },
  {
    id: 'progress-adventurous-01',
    context: 'progress',
    text: 'You have already traveled through plenty of number puzzles.',
    voices: ['adventurous'],
  },
  {
    id: 'progress-inventive-01',
    context: 'progress',
    text: 'The pattern of your practice is taking shape.',
    voices: ['inventive'],
  },
] as const satisfies readonly DialoguePhrase[];

const SIGNATURE_PHRASES = [
  {
    id: 'sunny-home-01',
    context: 'home',
    text: 'A bright little round could warm up the day.',
    companionIds: ['cozy-cats:sunny'],
  },
  {
    id: 'sunny-setup-01',
    context: 'setup',
    text: 'Sunny says every challenge looks better with a bright start.',
    companionIds: ['cozy-cats:sunny'],
  },
  {
    id: 'sunny-results-01',
    context: 'results',
    text: 'A little practice can brighten the whole day.',
    companionIds: ['cozy-cats:sunny'],
  },
  {
    id: 'cloud-home-01',
    context: 'home',
    text: 'Cloud saved a soft spot for some quiet practice.',
    companionIds: ['cozy-cats:cloud'],
  },
  {
    id: 'cloud-setup-01',
    context: 'setup',
    text: 'One question at a time is a lovely pace.',
    companionIds: ['cozy-cats:cloud'],
  },
  {
    id: 'cloud-results-01',
    context: 'results',
    text: 'Cloud thinks that round felt light and steady.',
    companionIds: ['cozy-cats:cloud'],
  },
  {
    id: 'biscuit-home-01',
    context: 'home',
    text: 'Biscuit has a fresh batch of questions ready.',
    companionIds: ['cozy-cats:biscuit'],
  },
  {
    id: 'biscuit-setup-01',
    context: 'setup',
    text: 'Mix the settings until the challenge is just right.',
    companionIds: ['cozy-cats:biscuit'],
  },
  {
    id: 'biscuit-results-01',
    context: 'results',
    text: 'Fresh practice, nicely done!',
    companionIds: ['cozy-cats:biscuit'],
  },
  {
    id: 'juniper-home-01',
    context: 'home',
    text: 'Juniper knows that skills grow a little every day.',
    companionIds: ['cozy-cats:juniper'],
  },
  {
    id: 'juniper-setup-01',
    context: 'setup',
    text: 'Choose one small skill to help grow stronger.',
    companionIds: ['cozy-cats:juniper'],
  },
  {
    id: 'juniper-results-01',
    context: 'results',
    text: 'Small steps grow into strong skills.',
    companionIds: ['cozy-cats:juniper'],
  },
  {
    id: 'moonbeam-home-01',
    context: 'home',
    text: 'Moonbeam found a quiet path through the numbers.',
    companionIds: ['cozy-cats:moonbeam'],
  },
  {
    id: 'moonbeam-setup-01',
    context: 'setup',
    text: 'Choose a challenge and let the answers find their glow.',
    companionIds: ['cozy-cats:moonbeam'],
  },
  {
    id: 'moonbeam-results-01',
    context: 'results',
    text: 'Those answers were shining tonight.',
    companionIds: ['cozy-cats:moonbeam'],
  },
  {
    id: 'patches-home-01',
    context: 'home',
    text: 'Patches is ready to add some color to practice.',
    companionIds: ['cozy-cats:patches'],
  },
  {
    id: 'patches-setup-01',
    context: 'setup',
    text: 'Pick a challenge and see what kind of picture it makes.',
    companionIds: ['cozy-cats:patches'],
  },
  {
    id: 'patches-results-01',
    context: 'results',
    text: 'Every try adds something to the picture.',
    companionIds: ['cozy-cats:patches'],
  },
  {
    id: 'gizmo-home-01',
    context: 'home',
    text: 'Gizmo has the number machine warmed up.',
    companionIds: ['cozy-cats:gizmo'],
  },
  {
    id: 'gizmo-setup-01',
    context: 'setup',
    text: 'Adjust the challenge and let us test the settings.',
    companionIds: ['cozy-cats:gizmo'],
  },
  {
    id: 'gizmo-results-01',
    context: 'results',
    text: 'That round gave the gears a good spin.',
    companionIds: ['cozy-cats:gizmo'],
  },
  {
    id: 'pepper-home-01',
    context: 'home',
    text: 'Pepper spotted a fresh trail of number puzzles.',
    companionIds: ['cozy-cats:pepper'],
  },
  {
    id: 'pepper-setup-01',
    context: 'setup',
    text: 'Choose your trail. Pepper is ready to explore.',
    companionIds: ['cozy-cats:pepper'],
  },
  {
    id: 'pepper-results-01',
    context: 'results',
    text: 'That was a bold run. Ready for another trail?',
    companionIds: ['cozy-cats:pepper'],
  },
  {
    id: 'aurora-home-01',
    context: 'home',
    text: 'Aurora brought a ribbon of color to the Nook.',
    companionIds: ['cozy-cats:aurora'],
  },
  {
    id: 'aurora-setup-01',
    context: 'setup',
    text: 'Choose a challenge and paint a bright path through it.',
    companionIds: ['cozy-cats:aurora'],
  },
  {
    id: 'aurora-results-01',
    context: 'results',
    text: 'Your practice left a bright trail behind it.',
    companionIds: ['cozy-cats:aurora'],
  },
  {
    id: 'comet-home-01',
    context: 'home',
    text: 'Comet is ready to race across another number sky.',
    companionIds: ['cozy-cats:comet'],
  },
  {
    id: 'comet-setup-01',
    context: 'setup',
    text: 'Set a course for the challenge you want today.',
    companionIds: ['cozy-cats:comet'],
  },
  {
    id: 'comet-results-01',
    context: 'results',
    text: 'That round really moved!',
    companionIds: ['cozy-cats:comet'],
  },
  {
    id: 'button-bunny-home-01',
    context: 'home',
    text: 'Button Bunny tucked a cozy challenge into the Nook.',
    companionIds: ['special-guests:button-bunny'],
  },
  {
    id: 'button-bunny-setup-01',
    context: 'setup',
    text: 'Pick a round and Button Bunny will stick close by.',
    companionIds: ['special-guests:button-bunny'],
  },
  {
    id: 'button-bunny-results-01',
    context: 'results',
    text: 'That practice came together one stitch at a time.',
    companionIds: ['special-guests:button-bunny'],
  },
] as const satisfies readonly DialoguePhrase[];

export const DIALOGUE_PHRASES = [
  ...SHARED_HOME_PHRASES,
  ...SHARED_SETUP_PHRASES,
  ...SHARED_RESULT_PHRASES,
  ...SHARED_CAPSULE_PHRASES,
  ...SHARED_EQUIP_PHRASES,
  ...SHARED_PROGRESS_PHRASES,
  ...SIGNATURE_PHRASES,
] as const satisfies readonly DialoguePhrase[];
